packages:
  - packages/*

nodeLinker: isolated

injectWorkspacePackages: true

dedupeInjectedDeps: false

syncInjectedDepsAfterScripts:
  - build
  - build:run

minimumReleaseAge: 1440

minimumReleaseAgeStrict: true

catalogs:
  template-typescript:
    typescript: npm:@typescript/typescript6@^6.0.2
    typescript-7: npm:typescript@^7.0.2

catalog:
  "@hono/node-server": ^2.0.6
  "@playwright/test": ^1.61.1
  "@tailwindcss/vite": ^4.3.2
  "@types/node": ^24.13.3
  "@types/web-bluetooth": ^0.0.21
  "@vitejs/plugin-vue": ^6.0.7
  "@vikejs/hono": ^0.2.1
  "@vue/tsconfig": ^0.9.1
  drizzle-kit: 1.0.0-rc.4
  drizzle-orm: 1.0.0-rc.4
  execa: ^9.6.1
  hono: ^4.12.27
  oxfmt: ^0.58.0
  oxlint: ^1.73.0
  oxlint-tsgolint: ^0.24.0
  pinia: ^3.0.4
  srvx: ^0.11.21
  tailwindcss: ^4.3.2
  telefunc: ^0.2.22
  tsc-alias: ^1.8.17
  tsx: ^4.23.0
  turbo: 2.10.2
  typescript: npm:@typescript/typescript6@^6.0.2
  typescript-6: npm:typescript@^6.0.3
  typescript-7: npm:typescript@^7.0.2
  valibot: ^1.4.2
  vite: ^8.1.4
  vike: ^0.4.260
  vike-vue: ^0.9.12
  vitest: ^4.1.10
  vue: ^3.5.39
  vue-tsc: ^3.3.6
  yaml: ^2.9.0

allowBuilds:
  esbuild: true
