import { mkdir, readdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { renderProject, type RenderOperation } from "./renderer.js";

const features = [
  "root-check",
  "fix-command",
  "devcontainer",
  "github-actions",
  "dependabot",
  "rustfmt-clippy",
  "cargo-test",
  "native-binary-release"
] as const;

const generatedBy = {
  packageName: "@ykdz/template",
  version: "0.0.0",
  command: "template init --preset rust-bin"
};

function cargoPackageNameFromDir(targetDir: string): string {
  const directoryName = path.basename(path.resolve(targetDir));
  const slug = directoryName
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return slug || "rust-bin";
}

async function assertNewOrEmptyDirectory(targetDir: string): Promise<void> {
  await mkdir(targetDir, { recursive: true });
  const entries = await readdir(targetDir);

  if (entries.length > 0) {
    throw new Error(`Target directory is not empty: ${targetDir}`);
  }
}

function cargoToml(projectName: string): string {
  return [
    "[package]",
    `name = "${projectName}"`,
    'version = "0.1.0"',
    'edition = "2024"',
    "",
    "[dependencies]",
    "",
    "[lints]",
    "workspace = true",
    "",
    "[workspace]",
    'members = ["."]',
    'resolver = "3"',
    "",
    "[workspace.lints.rust]",
    'unsafe_code = "forbid"',
    "",
    "[workspace.lints.clippy]",
    'all = "deny"',
    'pedantic = "deny"',
    'nursery = "deny"',
    "",
    "[profile.release]",
    'strip = "symbols"',
    'lto = "thin"',
    "codegen-units = 1",
    ""
  ].join("\n");
}

function cargoLock(projectName: string): string {
  return [
    "# This file is automatically @generated by Cargo.",
    "# It is not intended for manual editing.",
    "version = 4",
    "",
    "[[package]]",
    `name = "${projectName}"`,
    'version = "0.1.0"',
    ""
  ].join("\n");
}

function operationsForRustBin(projectName: string): RenderOperation[] {
  return [
    {
      kind: "writeText",
      to: "Cargo.toml",
      text: cargoToml(projectName)
    },
    {
      kind: "writeText",
      to: "Cargo.lock",
      text: cargoLock(projectName)
    },
    {
      kind: "writeText",
      to: "rustfmt.toml",
      text: ['edition = "2024"', "max_width = 100", ""].join("\n")
    },
    {
      kind: "writeText",
      to: ".gitignore",
      text: ["target", ".env", ""].join("\n")
    },
    {
      kind: "copyFile",
      from: "src/main.rs",
      to: "src/main.rs"
    },
    {
      kind: "writeText",
      to: "scripts/check",
      text: [
        "#!/usr/bin/env sh",
        "set -eu",
        "",
        "echo cargo fmt --all -- --check",
        "cargo fmt --all -- --check",
        "echo cargo clippy --workspace --all-targets -- -D warnings",
        "cargo clippy --workspace --all-targets -- -D warnings",
        "echo cargo test --workspace",
        "cargo test --workspace",
        ""
      ].join("\n")
    },
    {
      kind: "setExecutable",
      path: "scripts/check",
      executable: true
    },
    {
      kind: "writeJson",
      to: ".project-kit/blueprint.json",
      value: {
        schemaVersion: 1,
        preset: "rust-bin",
        projectKind: "single-package",
        features
      }
    },
    {
      kind: "writeJson",
      to: ".project-kit/generated-by.json",
      value: generatedBy
    },
    {
      kind: "writeJson",
      to: ".devcontainer/devcontainer.json",
      value: {
        name: `${projectName} Rust development`,
        image: "mcr.microsoft.com/devcontainers/rust:1",
        mounts: [
          "source=${localWorkspaceFolderBasename}-cargo-registry,target=/usr/local/cargo/registry,type=volume",
          "source=${localWorkspaceFolderBasename}-cargo-git,target=/usr/local/cargo/git,type=volume",
          "source=${localWorkspaceFolderBasename}-target,target=${containerWorkspaceFolder}/target,type=volume"
        ],
        postCreateCommand: "rustup component add rustfmt clippy && cargo fetch",
        customizations: {
          vscode: {
            extensions: ["rust-lang.rust-analyzer", "tamasfe.even-better-toml"]
          }
        }
      }
    },
    {
      kind: "writeText",
      to: ".github/workflows/check.yml",
      text: [
        "name: Check",
        "",
        "on:",
        "  pull_request:",
        "  push:",
        "    branches:",
        "      - main",
        "",
        "jobs:",
        "  check:",
        "    runs-on: ubuntu-latest",
        "    steps:",
        "      - uses: actions/checkout@v4",
        "      - uses: dtolnay/rust-toolchain@stable",
        "        with:",
        "          components: rustfmt, clippy",
        "      - uses: Swatinem/rust-cache@v2",
        "      - run: ./scripts/check",
        ""
      ].join("\n")
    },
    {
      kind: "writeText",
      to: ".github/dependabot.yml",
      text: [
        "version: 2",
        "updates:",
        "  - package-ecosystem: cargo",
        "    directory: /",
        "    schedule:",
        "      interval: weekly",
        "  - package-ecosystem: github-actions",
        "    directory: /",
        "    schedule:",
        "      interval: weekly",
        ""
      ].join("\n")
    }
  ];
}

function templateSourceRoot(): string {
  return path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "templates", "rust-bin");
}

export async function initRustBinProject(targetDir: string): Promise<void> {
  await assertNewOrEmptyDirectory(targetDir);

  await renderProject({
    sourceRoot: templateSourceRoot(),
    targetRoot: targetDir,
    operations: operationsForRustBin(cargoPackageNameFromDir(targetDir))
  });
}
