import path from "node:path";
import { fileURLToPath } from "node:url";
import { devcontainerNodeFeature } from "./devcontainer.js";
import type { ProjectBlueprint } from "./declarations.js";
import { assembleGenerationContext, type GenerationContext } from "./generation-context.js";
import {
  planRustBinChecks,
  planRustBinFixes,
  renderFixCommand,
  renderRootCheckCommand,
} from "./module-graph.js";
import { projectPresetDependabotConfig, projectRustBinGithubCheckWorkflow } from "./project-github.js";
import { renderNewProject, type RenderOperation } from "./renderer.js";
import { resolveToolchainVersions } from "./toolchain-resolution.js";

const features = [
  "root-check",
  "fix-command",
  "devcontainer",
  "github-actions",
  "dependabot",
  "rustfmt-clippy",
  "cargo-test"
] as const;

const generatedBy = {
  packageName: "@ykdz/template",
  version: "0.0.0",
  command: "template init --preset rust-bin"
};

type InitRustBinProjectOptions = {
  readonly generationContext?: GenerationContext;
};

const rustBinBlueprint: ProjectBlueprint = {
  schemaVersion: 1,
  preset: "rust-bin",
  packageManager: "pnpm",
  projectKind: "single-package",
  features: [...features],
};

function cargoPackageNameFromDir(targetDir: string): string {
  const directoryName = path.basename(path.resolve(targetDir));
  const slug = directoryName
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return slug || "rust-bin";
}

function cargoToml(projectName: string): string {
  return [
    "[package]",
    `name = "${projectName}"`,
    'version = "0.1.0"',
    'edition = "2024"',
    "",
    "[dependencies]",
    "",
    "[lints]",
    "workspace = true",
    "",
    "[workspace]",
    'members = ["."]',
    'resolver = "3"',
    "",
    "[workspace.lints.rust]",
    'unsafe_code = "forbid"',
    "",
    "[workspace.lints.clippy]",
    'all = "deny"',
    'pedantic = "deny"',
    'nursery = "deny"',
    "",
    "[profile.release]",
    'strip = "symbols"',
    'lto = "thin"',
    "codegen-units = 1",
    ""
  ].join("\n");
}

function cargoLock(projectName: string): string {
  return [
    "# This file is automatically @generated by Cargo.",
    "# It is not intended for manual editing.",
    "version = 4",
    "",
    "[[package]]",
    `name = "${projectName}"`,
    'version = "0.1.0"',
    ""
  ].join("\n");
}

export function projectRustBinPackageScripts(): Record<string, string> {
  return {
    check: renderRootCheckCommand(planRustBinChecks()),
    fix: renderFixCommand(planRustBinFixes()),
  };
}

function packageJson(context: GenerationContext, projectName: string): Record<string, unknown> {
  return {
    name: projectName,
    version: "0.0.0",
    private: true,
    scripts: projectRustBinPackageScripts(),
    engines: {
      node: context.toolchain.nodeLtsMajor.value,
    },
    packageManager: context.toolchain.packageManagerPin.value,
  };
}

function generationRecord(context: GenerationContext): Record<string, unknown> {
  return {
    ...generatedBy,
    toolchain: {
      nodeLtsMajor: context.toolchain.nodeLtsMajor.value,
      packageManagerPin: context.toolchain.packageManagerPin.value,
      source: context.toolchain.source,
    },
  };
}

function operationsForRustBin(context: GenerationContext, projectName: string): RenderOperation[] {
  return [
    {
      kind: "writeJson",
      to: "package.json",
      value: packageJson(context, projectName),
    },
    {
      kind: "writeText",
      to: "pnpm-workspace.yaml",
      text: ["packages:", "  - .", ""].join("\n"),
    },
    {
      kind: "writeText",
      to: "Cargo.toml",
      text: cargoToml(projectName)
    },
    {
      kind: "writeText",
      to: "Cargo.lock",
      text: cargoLock(projectName)
    },
    {
      kind: "writeText",
      to: "rustfmt.toml",
      text: ['edition = "2024"', "max_width = 100", ""].join("\n")
    },
    {
      kind: "writeText",
      to: ".gitignore",
      text: ["target", ".env", ""].join("\n")
    },
    {
      kind: "copyFile",
      from: "src/main.rs",
      to: "src/main.rs"
    },
    {
      kind: "writeJson",
      to: ".project-kit/blueprint.json",
      value: rustBinBlueprint
    },
    {
      kind: "writeJson",
      to: ".project-kit/generated-by.json",
      value: generationRecord(context)
    },
    {
      kind: "writeJson",
      to: ".devcontainer/devcontainer.json",
      value: {
        name: `${projectName} Rust development`,
        image: "mcr.microsoft.com/devcontainers/rust:1",
        features: devcontainerNodeFeature({
          nodeVersion: context.toolchain.nodeLtsMajor.value,
          packageManagerPin: context.toolchain.packageManagerPin.value,
        }),
        mounts: [
          "source=${localWorkspaceFolderBasename}-cargo-registry,target=/usr/local/cargo/registry,type=volume",
          "source=${localWorkspaceFolderBasename}-cargo-git,target=/usr/local/cargo/git,type=volume",
          "source=${localWorkspaceFolderBasename}-target,target=${containerWorkspaceFolder}/target,type=volume"
        ],
        customizations: {
          vscode: {
            extensions: ["rust-lang.rust-analyzer", "tamasfe.even-better-toml"]
          }
        }
      }
    },
    {
      kind: "writeText",
      to: ".github/workflows/check.yml",
      text: projectRustBinGithubCheckWorkflow(),
    },
    {
      kind: "writeText",
      to: ".github/dependabot.yml",
      text: projectPresetDependabotConfig("rust-bin"),
    }
  ];
}

function templateSourceRoot(): string {
  return path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "templates", "rust-bin");
}

export async function initRustBinProject(
  targetDir: string,
  options?: InitRustBinProjectOptions,
): Promise<void> {
  const generationContext =
    options?.generationContext ??
    assembleGenerationContext({
      targetDir,
      blueprint: rustBinBlueprint,
      toolchain: await resolveToolchainVersions(),
    });
  const projectName = cargoPackageNameFromDir(targetDir);

  await renderNewProject({
    sourceRoot: templateSourceRoot(),
    targetRoot: targetDir,
    operations: operationsForRustBin(generationContext, projectName)
  });
}
