import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import type {
  BuiltInPreset,
  ProjectBlueprint,
} from "../../src/declarations.js";
import { devcontainerNodeFeature } from "../../src/devcontainer.js";
import { editorCustomizationForCapabilities } from "../../src/editor-customization.js";
import type { GenerationContext } from "../../src/generation-context.js";
import {
  type CheckPlan,
  type ComponentOwner,
  type FixPlan,
  renderFixCommand,
  renderRootCheckCommand,
} from "../../src/module-graph.js";
import type {
  PresetProjection,
  PresetProjectionPlan,
} from "../../src/preset-projection.js";
import {
  projectCheckWorkflow,
  projectDependabotConfig,
  type DependencyMaintenancePolicy,
} from "../../src/project-github.js";
import { renderNewProject, type RenderOperation } from "../../src/renderer.js";

const generatedBy = {
  packageName: "@ykdz/template",
  version: "0.0.0",
  command: "template init --preset rust-bin",
};

export const rustBinPresetMetadata: BuiltInPreset = {
  name: "rust-bin",
  title: "Rust binary",
  description:
    "Single-package Rust native binary with rustfmt, clippy, and cargo tests.",
  generation: "supported",
  supportedPackageManagers: ["pnpm"],
  supportedProjectKinds: ["single-package"],
  features: [
    "root-check",
    "fix-command",
    "devcontainer",
    "github-actions",
    "dependabot",
    "rustfmt-clippy",
    "cargo-test",
  ],
};

const dependencyMaintenancePolicy: DependencyMaintenancePolicy = {
  ecosystems: ["npm", "cargo", "github-actions"],
  interval: "weekly",
};

const rustPackageBoundary: ComponentOwner = {
  kind: "package-boundary",
  path: ".",
};

function cargoPackageNameFromProjectName(projectName: string): string {
  const slug = projectName
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return slug || "rust-bin";
}

export function planRustBinChecks(): CheckPlan {
  return {
    components: [
      { kind: "rustfmt-check", owner: rustPackageBoundary },
      { kind: "cargo-clippy", owner: rustPackageBoundary },
      { kind: "cargo-test", owner: rustPackageBoundary },
    ],
    environmentNeeds: [],
  };
}

export function planRustBinFixes(): FixPlan {
  return {
    components: [{ kind: "rustfmt-write", owner: rustPackageBoundary }],
  };
}

export function rustBinBlueprint(): ProjectBlueprint {
  return {
    schemaVersion: 1,
    preset: "rust-bin",
    packageManager: "pnpm",
    projectKind: "single-package",
    features: [...rustBinPresetMetadata.features],
  };
}

export function projectRustBinPackageScripts(): Record<string, string> {
  return {
    check: renderRootCheckCommand(planRustBinChecks()),
    fix: renderFixCommand(planRustBinFixes()),
  };
}

function cargoToml(projectName: string): string {
  return [
    "[package]",
    `name = "${projectName}"`,
    'version = "0.1.0"',
    'edition = "2024"',
    "",
    "[dependencies]",
    "",
    "[lints]",
    "workspace = true",
    "",
    "[workspace]",
    'members = ["."]',
    'resolver = "3"',
    "",
    "[workspace.lints.rust]",
    'unsafe_code = "forbid"',
    "",
    "[workspace.lints.clippy]",
    'all = "deny"',
    'pedantic = "deny"',
    'nursery = "deny"',
    "",
    "[profile.release]",
    'strip = "symbols"',
    'lto = "thin"',
    "codegen-units = 1",
    "",
  ].join("\n");
}

function cargoLock(projectName: string): string {
  return [
    "# This file is automatically @generated by Cargo.",
    "# It is not intended for manual editing.",
    "version = 4",
    "",
    "[[package]]",
    `name = "${projectName}"`,
    'version = "0.1.0"',
    "",
  ].join("\n");
}

function packageJson(
  context: GenerationContext,
  projectName: string,
  packageScripts: Record<string, string>,
): Record<string, unknown> {
  return {
    name: projectName,
    version: "0.0.0",
    private: true,
    scripts: packageScripts,
    engines: {
      node: context.toolchain.nodeLtsMajor.value,
    },
    packageManager: context.toolchain.packageManagerPin.value,
  };
}

function generationRecord(context: GenerationContext): Record<string, unknown> {
  return {
    ...generatedBy,
    toolchain: {
      nodeLtsMajor: context.toolchain.nodeLtsMajor.value,
      packageManagerPin: context.toolchain.packageManagerPin.value,
      source: context.toolchain.source,
    },
  };
}

function operationsForRustBin(
  context: GenerationContext,
  projectName: string,
  packageScripts: Record<string, string>,
  checkPlan: CheckPlan,
): RenderOperation[] {
  const editorCustomization = editorCustomizationForCapabilities([
    "rust-tooling",
  ]);

  return [
    {
      kind: "writeJson",
      to: "package.json",
      value: packageJson(context, projectName, packageScripts),
    },
    {
      kind: "writeText",
      to: "pnpm-workspace.yaml",
      text: ["packages:", "  - .", ""].join("\n"),
    },
    {
      kind: "writeText",
      to: "Cargo.toml",
      text: cargoToml(projectName),
    },
    {
      kind: "writeText",
      to: "Cargo.lock",
      text: cargoLock(projectName),
    },
    {
      kind: "writeText",
      to: "rustfmt.toml",
      text: ['edition = "2024"', "max_width = 100", ""].join("\n"),
    },
    {
      kind: "writeText",
      to: ".gitignore",
      text: ["target", ".env", ""].join("\n"),
    },
    {
      kind: "copyFile",
      from: "src/main.rs",
      to: "src/main.rs",
    },
    {
      kind: "writeJson",
      to: ".project-kit/blueprint.json",
      value: rustBinBlueprint(),
    },
    {
      kind: "writeJson",
      to: ".project-kit/generated-by.json",
      value: generationRecord(context),
    },
    {
      kind: "writeJson",
      to: ".devcontainer/devcontainer.json",
      value: {
        name: `${projectName} Rust development`,
        image: "mcr.microsoft.com/devcontainers/rust:1",
        features: devcontainerNodeFeature({
          nodeVersion: context.toolchain.nodeLtsMajor.value,
          packageManagerPin: context.toolchain.packageManagerPin.value,
        }),
        mounts: [
          "source=${localWorkspaceFolderBasename}-cargo-registry,target=/usr/local/cargo/registry,type=volume",
          "source=${localWorkspaceFolderBasename}-cargo-git,target=/usr/local/cargo/git,type=volume",
          "source=${localWorkspaceFolderBasename}-target,target=${containerWorkspaceFolder}/target,type=volume",
        ],
        customizations: {
          vscode: {
            extensions: editorCustomization.extensions,
            settings: editorCustomization.settings,
          },
        },
      },
    },
    {
      kind: "writeJson",
      to: ".vscode/extensions.json",
      value: {
        recommendations: editorCustomization.extensions,
      },
    },
    {
      kind: "writeJson",
      to: ".vscode/settings.json",
      value: editorCustomization.settings,
    },
    {
      kind: "writeText",
      to: ".github/workflows/check.yml",
      text: projectCheckWorkflow({
        checkPlan,
        environmentPreparation: { rustToolchain: true },
      }),
    },
    {
      kind: "writeText",
      to: ".github/dependabot.yml",
      text: projectDependabotConfig(dependencyMaintenancePolicy),
    },
  ];
}

function templateSourceRoot(): string {
  const projectionDir = path.dirname(fileURLToPath(import.meta.url));
  const publishedTemplateRoot = path.join(
    projectionDir,
    "..",
    "..",
    "..",
    "templates",
    "rust-bin",
  );

  return existsSync(path.join(publishedTemplateRoot, "src", "main.rs"))
    ? publishedTemplateRoot
    : projectionDir;
}

export const rustBinPresetProjection: PresetProjection = {
  metadata: rustBinPresetMetadata,
  blueprint: rustBinBlueprint,
  project(context: GenerationContext): PresetProjectionPlan {
    const checkPlan = planRustBinChecks();
    const fixPlan = planRustBinFixes();
    const packageScripts = projectRustBinPackageScripts();
    const projectName = cargoPackageNameFromProjectName(
      context.projectName.value,
    );

    return {
      sourceRoot: templateSourceRoot(),
      operations: operationsForRustBin(
        context,
        projectName,
        packageScripts,
        checkPlan,
      ),
      checkPlan,
      fixPlan,
      dependencyMaintenancePolicy,
      packageScripts,
      capabilities: {
        rootCheck: true,
        fixCommand: true,
        githubActions: true,
        dependabot: true,
        devcontainer: true,
      },
    };
  },
  async render({ targetDir, plan }): Promise<void> {
    await renderNewProject({
      sourceRoot: plan.sourceRoot,
      sourceRoots: plan.sourceRoots,
      targetRoot: targetDir,
      operations: [...plan.operations],
    });
  },
};
