name: Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - run: corepack enable
      - run: pnpm install
      - run: pnpm --filter ./apps/web exec playwright install --with-deps chromium
      - run: pnpm run check
